name: 5511assignment1
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - alembic==1.14.1
      - branca==0.8.1
      - colorlog==6.9.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - filelock==3.17.0
      - fonttools==4.55.3
      - fsspec==2025.2.0
      - gensim==4.3.3
      - greenlet==3.1.1
      - huggingface-hub==0.28.1
      - importlib-resources==6.5.2
      - joblib==1.4.2
      - jsonpickle==4.0.1
      - kiwisolver==1.4.7
      - lightgbm==4.5.0
      - llvmlite==0.43.0
      - mako==1.3.9
      - matplotlib==3.9.4
      - mlxtend==0.23.4
      - mpmath==1.3.0
      - networkx==3.2.1
      - numba==0.60.0
      - numpy==1.26.4
      - optuna==4.2.1
      - pandas==2.2.3
      - py4j==0.10.9.7
      - pyarrow==18.0.0
      - pynndescent==0.5.13
      - pyparsing==3.2.1
      - python-slugify==8.0.4
      - pytz==2024.2
      - pyvis==0.3.2
      - regex==2024.11.6
      - safetensors==0.5.2
      - scikit-learn==1.5.2
      - scikit-learn-extra==0.3.0
      - scipy==1.13.1
      - seaborn==0.13.2
      - sentence-transformers==2.5.1
      - smart-open==7.1.0
      - sqlalchemy==2.0.38
      - stats==0.1.2a0
      - sympy==1.13.1
      - tabulate==0.9.0
      - text-unidecode==1.3
      - threadpoolctl==3.5.0
      - tokenizers==0.21.0
      - tqdm==4.67.0
      - transformers==4.48.3
      - tzdata==2024.2
      - umap==0.1.1
      - umap-learn==0.5.7
      - wrapt==1.17.2
